# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
baseurl: "/microcast" # repository name
url: "http://soitscometothis.net" # Either custom domain or http://GithubUsername.github.io

# Can I delete these or are they still needed?
twitter_username: LK64076007A
github_username:  LK64076007A  

# Podcast Feed Settings
title:          "Driftwood" # name of your podcast
email:          michael@laccheo.com # CHANGE
description:    "A short form podcast hosted completely on Github." # CHANGE
subtitle:       "Size isn't everything" # CHANGE
lang:           en-us
author:         Michael # CHANGE
copyright:      "&#x2117; &amp; &#xA9; 2016"


# Outputting
permalink: /:title/

# Build settings
markdown: kramdown
timezone: America/New_York

# Basic

# Navigation
nav:
  - name:           "About"
    href:           "/microcast/about" # CHANGE to match your repository
  - name:           "Feed"
    href:           "/microcast/podcast.rss" # CHANGE to match your repository
  - name:           "iTunes"
    href:           "https://itunes.apple.com/us/podcast/driftwood/id1080157963" #CHANGE
  - name:           "Overcast"
    href:           "https://overcast.fm/itunes1080157963/driftwood" # CHANGE

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
