# Site settings
title: 萤火小时光
email: 1091738575@qq.com
description: > # this means to ignore newlines until "baseurl:"
  有些歌被翻唱之后成为了经典，有些经典被翻唱之后却另有一番味道。静静地聆听，一秒倾心。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://three.sh" # the base hostname & protocol for your site
twitter_username:
github_username:
weibo_username: 

# Build settings
markdown: kramdown
